# Generated by Django 3.1.7 on 2021-04-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
