# Generated by Django 3.1.8 on 2021-04-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
