# Generated by Django 3.1.8 on 2021-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_auto_20210411_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='category',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='page',
            field=models.CharField(choices=[('Massage', 'Massage'), ('Sex Coaching', 'Sex Coaching'), ('Life Coaching', 'Life Coaching'), ('Shadow Work', 'Shadow Work'), ('Workshops', 'Workshops')], default='Massage', max_length=13),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
