# Generated by Django 3.1.8 on 2021-04-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_auto_20210412_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
