# Generated by Django 3.1.8 on 2021-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='therapist',
            field=models.CharField(max_length=254),
        ),
    ]
