# Generated by Django 3.1.8 on 2021-04-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20210423_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.category'),
        ),
    ]
