# Generated by Django 3.1.8 on 2021-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210419_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link to read blog post', max_length=255),
        ),
    ]
