# Generated by Django 3.1.8 on 2021-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('age', models.CharField(max_length=2, null=True)),
                ('about', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors')),
            ],
            options={
                'verbose_name_plural': 'Therapists Profiles',
            },
        ),
    ]
