# Generated by Django 3.1.8 on 2021-04-12 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.CharField(choices=[('Massage', 'Massage'), ('Sex Coaching', 'Sex Coaching'), ('Life Coaching', 'Life Coaching'), ('Shadow Work', 'Shadow Work'), ('Workshops', 'Workshops')], default='Massage', max_length=13)),
            ],
        ),
    ]
